tunnel: f5d9e81b-816e-4a92-9cf9-e937273a8952
credentials-file: C:\Users\Nio\.cloudflared\f5d9e81b-816e-4a92-9cf9-e937273a8952.json

ingress:
  # Route ke Next.js Frontend (Port 3000)
  - hostname: sfinity.ryuzen.my.id
    service: http://127.0.0.1:3000

  # Route ke Node.js Backend API (Port 5000)
  - hostname: api-sfinity.ryuzen.my.id
    service: http://127.0.0.1:5000

  # Fallback catch-all (mengembalikan 404 jika ada request subdomain lain)
  - service: http_status:404
